### ISSUE TITLE
Old Man Features

### ISSUE THREAD

**Issue by oOKexOo** [zen-mod/ZEN#389]
**List of possible features to adapt from Old Man**
- [ ] Malaria-infected civilians. #384 
- [ ] CSAT science textures for Tempest and Taru. #387 
- [ ] Music tracks. #385
- [ ] Undercover framework. Possibly related to #310.
- [ ] Checkpoint module.
- [ ] Immersive sound for intel acquisition (from dead enemies and computers).
- [ ] Intels that can be put in an inventory (USB stick, documents and access cards).

**Comment by oOKexOo** [comment]
Well, apparently the checkpoint and relationship frameworks are not really that MP compatible, not that I'm too surprised. Moreover, a lot seems to be hard-coded  (_e.g._ uniform classes, etc.), and thus not generally applicable. Basically, adapting them will likely be quite cumbersome.
